apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: chatbot-test-app-62-gitops
  description: This is GitOps manifest for chatbot-test-app-62   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=chatbot-test-app-62
    janus-idp.io/tekton: chatbot-test-app-62 
    backstage.io/kubernetes-id: chatbot-test-app-62 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:default/michael-valdron 
  lifecycle: experimental
  dependsOn:
    - component:chatbot-test-app-62  
